import sqlite3
import unittest

from scripts.postgres_migration import (
    ColumnSchema,
    DataFingerprint,
    MigrationError,
    coerce_value,
    create_foreign_key_sql,
    create_index_sql,
    create_table_sql,
    inspect_sqlite_schema,
    map_postgres_type,
    postgres_default,
    safe_object_name,
)


class PostgresMigrationTests(unittest.TestCase):
    def setUp(self):
        self.db = sqlite3.connect(":memory:")
        self.db.execute("PRAGMA foreign_keys = ON")
        self.db.executescript(
            """
            CREATE TABLE parents (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL UNIQUE,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE children (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                parent_id INTEGER NOT NULL,
                label TEXT NOT NULL DEFAULT 'queued',
                score REAL DEFAULT 0.5,
                FOREIGN KEY(parent_id) REFERENCES parents(id) ON DELETE CASCADE,
                UNIQUE(parent_id, label)
            );
            CREATE INDEX idx_children_label ON children(lower(label), id DESC);
            CREATE TABLE memberships (
                parent_id INTEGER NOT NULL,
                child_id INTEGER NOT NULL,
                PRIMARY KEY(parent_id, child_id)
            );
            INSERT INTO parents (name) VALUES ('Alpha'), ('Beta');
            INSERT INTO children (parent_id, label, score) VALUES (1, 'One', 1.25), (2, 'Two', 2.5);
            """
        )

    def tearDown(self):
        self.db.close()

    def test_schema_introspection_preserves_keys_and_expression_index(self):
        schemas = {table.name: table for table in inspect_sqlite_schema(self.db)}
        self.assertEqual(set(schemas), {"children", "memberships", "parents"})
        self.assertEqual(schemas["parents"].identity_column, "id")
        self.assertEqual(schemas["memberships"].primary_key, ("parent_id", "child_id"))
        self.assertEqual(schemas["children"].foreign_keys[0].target_table, "parents")
        expression_index = next(
            index for index in schemas["children"].indexes if index.name == "idx_children_label"
        )
        self.assertTrue(expression_index.has_expression)
        rendered = create_index_sql("deepsift_shadow", schemas["children"], expression_index)
        self.assertIn('CREATE INDEX "idx_children_label" ON "deepsift_shadow"."children"', rendered)
        self.assertNotIn('"deepsift_shadow"."idx_children_label"', rendered)
        self.assertIn("lower(label)", rendered)
        self.assertIn("id DESC", rendered)

    def test_table_ddl_uses_identity_and_composite_primary_key(self):
        schemas = {table.name: table for table in inspect_sqlite_schema(self.db)}
        parent_sql = create_table_sql("deepsift_shadow", schemas["parents"])
        membership_sql = create_table_sql("deepsift_shadow", schemas["memberships"])
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", parent_sql)
        self.assertIn("to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'", parent_sql)
        self.assertIn('PRIMARY KEY ("parent_id", "child_id")', membership_sql)

    def test_foreign_key_ddl_is_qualified_and_validated_later(self):
        schemas = {table.name: table for table in inspect_sqlite_schema(self.db)}
        name, statement = create_foreign_key_sql(
            "deepsift_shadow",
            schemas["children"],
            schemas["children"].foreign_keys[0],
            1,
        )
        self.assertTrue(name.startswith("fk_children"))
        self.assertIn('REFERENCES "deepsift_shadow"."parents" ("id")', statement)
        self.assertIn("ON DELETE CASCADE", statement)
        self.assertTrue(statement.endswith("NOT VALID"))

    def test_fingerprint_is_order_independent_but_duplicate_sensitive(self):
        first = DataFingerprint()
        second = DataFingerprint()
        third = DataFingerprint()
        for row in [(1, "Alpha"), (2, "Beta")]:
            first.add(row)
        for row in [(2, "Beta"), (1, "Alpha")]:
            second.add(row)
        for row in [(1, "Alpha"), (2, "Beta"), (2, "Beta")]:
            third.add(row)
        self.assertTrue(first.matches(second))
        self.assertFalse(first.matches(third))

    def test_type_and_default_translation_reject_unknown_expressions(self):
        self.assertEqual(map_postgres_type("INTEGER"), "BIGINT")
        self.assertEqual(map_postgres_type("TEXT"), "TEXT")
        self.assertEqual(map_postgres_type("REAL"), "DOUBLE PRECISION")
        self.assertEqual(postgres_default("('queued')"), "'queued'")
        with self.assertRaises(MigrationError):
            postgres_default("datetime('now')")

    def test_value_coercion_matches_target_types(self):
        integer_column = ColumnSchema("attempts", "INTEGER", False, None, 0)
        text_column = ColumnSchema("name", "TEXT", False, None, 0)
        self.assertEqual(coerce_value(integer_column, "4"), 4)
        self.assertEqual(coerce_value(text_column, 12), "12")
        with self.assertRaises(MigrationError):
            coerce_value(integer_column, 2.25)

    def test_long_object_names_are_stable_and_within_postgres_limit(self):
        first = safe_object_name("idx", "x" * 100, "y" * 100)
        second = safe_object_name("idx", "x" * 100, "y" * 100)
        self.assertEqual(first, second)
        self.assertLessEqual(len(first), 63)


if __name__ == "__main__":
    unittest.main()
