import os
import types
import unittest
from unittest import mock

from database import (
    DatabaseConfigurationError,
    SQLiteCompatibleRow,
    configured_database_backend,
    database_savepoint,
    recover_failed_database_transaction,
    split_sql_script,
    translate_sql,
)


class DatabaseCompatibilityTests(unittest.TestCase):
    class FakePostgresConnection:
        backend = "postgres"

        def __init__(self, transaction_status="IDLE"):
            status = types.SimpleNamespace(name=transaction_status)
            self.raw_connection = types.SimpleNamespace(info=types.SimpleNamespace(transaction_status=status))
            self.statements = []
            self.rollback_calls = 0

        def execute(self, statement):
            self.statements.append(statement)

        def rollback(self):
            self.rollback_calls += 1

    def test_sqlite_compatible_row_supports_numeric_and_named_access(self):
        row = SQLiteCompatibleRow(("id", "name"), (7, "Alpha"))
        self.assertEqual(row[0], 7)
        self.assertEqual(row["name"], "Alpha")
        self.assertEqual(row.get("missing", "fallback"), "fallback")
        self.assertEqual(dict(row), {"id": 7, "name": "Alpha"})
        self.assertEqual(tuple(row), (7, "Alpha"))

    def test_qmark_translation_ignores_literals_and_escapes_percent(self):
        translated, count = translate_sql(
            "SELECT '?' AS literal FROM events WHERE payload LIKE '%click%' AND id = ?",
            has_parameters=True,
        )
        self.assertEqual(count, 1)
        self.assertIn("SELECT '?' AS literal", translated)
        self.assertIn("ILIKE '%%click%%'", translated)
        self.assertTrue(translated.endswith("id = %s"))

    def test_sqlite_functions_translate_outside_string_literals(self):
        translated, count = translate_sql(
            "SELECT datetime(created_at), date(created_at), GROUP_CONCAT(value, ', ') "
            "FROM events WHERE note = 'datetime(?)' AND id = ?",
            has_parameters=True,
        )
        self.assertEqual(count, 1)
        self.assertIn("ds_datetime(created_at)", translated)
        self.assertIn("ds_date(created_at)", translated)
        self.assertIn("STRING_AGG(value, ', ')", translated)
        self.assertIn("note = 'datetime(?)'", translated)

    def test_insert_or_ignore_becomes_postgres_conflict_clause(self):
        translated, count = translate_sql(
            "INSERT OR IGNORE INTO jobs (event_key, payload) VALUES (?, ?)",
            has_parameters=True,
        )
        self.assertEqual(count, 2)
        self.assertEqual(
            translated,
            "INSERT INTO jobs (event_key, payload) VALUES (%s, %s) ON CONFLICT DO NOTHING",
        )

    def test_ddl_translation_preserves_sqlite_integer_affinity_with_bigint(self):
        translated, count = translate_sql(
            """
            CREATE TABLE items (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                attempts INTEGER NOT NULL DEFAULT 0,
                score REAL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        self.assertEqual(count, 0)
        self.assertIn("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", translated)
        self.assertIn("attempts BIGINT", translated)
        self.assertIn("score DOUBLE PRECISION", translated)
        self.assertIn("to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'", translated)

    def test_script_split_keeps_semicolons_inside_strings(self):
        statements = split_sql_script("CREATE TABLE a (value TEXT DEFAULT ';'); INSERT INTO a VALUES ('x;y');")
        self.assertEqual(len(statements), 2)

    def test_script_split_removes_utf8_byte_order_marker(self):
        statements = split_sql_script("\ufeffPRAGMA foreign_keys = ON; CREATE TABLE a (id INTEGER);")
        self.assertEqual(statements[0], "PRAGMA foreign_keys = ON")
        self.assertEqual(statements[1], "CREATE TABLE a (id INTEGER)")

    def test_recover_failed_postgres_transaction_only_rolls_back_inerror(self):
        failed = self.FakePostgresConnection("INERROR")
        idle = self.FakePostgresConnection("IDLE")
        self.assertTrue(recover_failed_database_transaction(failed))
        self.assertEqual(failed.rollback_calls, 1)
        self.assertFalse(recover_failed_database_transaction(idle))
        self.assertEqual(idle.rollback_calls, 0)

    def test_postgres_savepoint_recovers_failed_optional_statement(self):
        connection = self.FakePostgresConnection()
        with self.assertRaisesRegex(ValueError, "expected"):
            with database_savepoint(connection, "optional_query"):
                raise ValueError("expected")
        self.assertEqual(
            connection.statements,
            [
                'SAVEPOINT "optional_query"',
                'ROLLBACK TO SAVEPOINT "optional_query"',
                'RELEASE SAVEPOINT "optional_query"',
            ],
        )

    def test_backend_defaults_to_sqlite_and_rejects_unknown_values(self):
        with mock.patch.dict(os.environ, {}, clear=True):
            self.assertEqual(configured_database_backend(), "sqlite")
        with mock.patch.dict(os.environ, {"CRM_DB_BACKEND": "postgresql"}, clear=True):
            self.assertEqual(configured_database_backend(), "postgres")
        with mock.patch.dict(os.environ, {"CRM_DB_BACKEND": "oracle"}, clear=True):
            with self.assertRaises(DatabaseConfigurationError):
                configured_database_backend()


if __name__ == "__main__":
    unittest.main()
